# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OffersForMeter(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_offersformeter: int=None, start_date: datetime=None, end_date: datetime=None):  # noqa: E501
        """OffersForMeter - a model defined in Swagger

        :param id_offersformeter: The id_offersformeter of this OffersForMeter.  # noqa: E501
        :type id_offersformeter: int
        :param start_date: The start_date of this OffersForMeter.  # noqa: E501
        :type start_date: datetime
        :param end_date: The end_date of this OffersForMeter.  # noqa: E501
        :type end_date: datetime
        """
        self.swagger_types = {
            'id_offersformeter': int,
            'start_date': datetime,
            'end_date': datetime
        }

        self.attribute_map = {
            'id_offersformeter': 'id_offersformeter',
            'start_date': 'start_date',
            'end_date': 'end_date'
        }
        self._id_offersformeter = id_offersformeter
        self._start_date = start_date
        self._end_date = end_date

    @classmethod
    def from_dict(cls, dikt) -> 'OffersForMeter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OffersForMeter of this OffersForMeter.  # noqa: E501
        :rtype: OffersForMeter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_offersformeter(self) -> int:
        """Gets the id_offersformeter of this OffersForMeter.

        A unique ID of an offer for meter.  # noqa: E501

        :return: The id_offersformeter of this OffersForMeter.
        :rtype: int
        """
        return self._id_offersformeter

    @id_offersformeter.setter
    def id_offersformeter(self, id_offersformeter: int):
        """Sets the id_offersformeter of this OffersForMeter.

        A unique ID of an offer for meter.  # noqa: E501

        :param id_offersformeter: The id_offersformeter of this OffersForMeter.
        :type id_offersformeter: int
        """

        self._id_offersformeter = id_offersformeter

    @property
    def start_date(self) -> datetime:
        """Gets the start_date of this OffersForMeter.

        Date from which the offer is active.  # noqa: E501

        :return: The start_date of this OffersForMeter.
        :rtype: datetime
        """
        return self._start_date

    @start_date.setter
    def start_date(self, start_date: datetime):
        """Sets the start_date of this OffersForMeter.

        Date from which the offer is active.  # noqa: E501

        :param start_date: The start_date of this OffersForMeter.
        :type start_date: datetime
        """

        self._start_date = start_date

    @property
    def end_date(self) -> datetime:
        """Gets the end_date of this OffersForMeter.

        Date from which the offer is inactive.  # noqa: E501

        :return: The end_date of this OffersForMeter.
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date: datetime):
        """Sets the end_date of this OffersForMeter.

        Date from which the offer is inactive.  # noqa: E501

        :param end_date: The end_date of this OffersForMeter.
        :type end_date: datetime
        """

        self._end_date = end_date
