name: Python Linting
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Build environment and install necessary dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run black
        run: |
          cd website
          black --check --verbose .         
      - name: Run flake
        run: |
          cd ..
          flake8    
          