name: black
on: push
jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - run: |
          python -m pip install --upgrade pip
          pip install black
      - run: |
          cd website
          black --verbose .
