name: Python Linting
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: Install necessary dependencies to lint
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install flake8
      - name: Run black
        run: |
          cd website
          black --check --verbose .         
      - name: Run flake
        run: |
          cd ..
          flake8 --extend-ignore E203,W291,E402,W503 --max-line-length 120
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
