name: clean code
on:
  push:
    branches:
      - main 
      - dev
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.12
      - name: install necessary dependencies to lint
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install flake8
      - name: run black
        run: |
          cd website
          black --check --verbose .         
      - name: run flake8
        run: |
          cd ..
          # flake8 --extend-ignore E203,W291,E402,W503 --max-line-length 120 --per-file-ignores="website/views.py:F401"
